// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiandpftwwdhimlfuacu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYW5kcGZ0d3dkaGltbGZ1YWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjM2ODgsImV4cCI6MjA2MTA5OTY4OH0.pDeL1eVkYJ7XbwVDkXv419Rx71Wx7jNeP6QKh99viGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);